#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: make
#
Name     : cpuid
Version  : 20230505
Release  : 36
URL      : https://www.etallen.com/cpuid/cpuid-20230505.src.tar.gz
Source0  : https://www.etallen.com/cpuid/cpuid-20230505.src.tar.gz
Summary  : dumps CPUID information about the CPU(s)
Group    : Development/Tools
License  : GPL-2.0
Requires: cpuid-bin = %{version}-%{release}
Requires: cpuid-license = %{version}-%{release}
Requires: cpuid-man = %{version}-%{release}
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
cpuid dumps detailed information about the CPU(s) gathered from the CPUID 
instruction, and also determines the exact model of CPU(s).

%package bin
Summary: bin components for the cpuid package.
Group: Binaries
Requires: cpuid-license = %{version}-%{release}

%description bin
bin components for the cpuid package.


%package license
Summary: license components for the cpuid package.
Group: Default

%description license
license components for the cpuid package.


%package man
Summary: man components for the cpuid package.
Group: Default

%description man
man components for the cpuid package.


%prep
%setup -q -n cpuid-20230505
cd %{_builddir}/cpuid-20230505
pushd ..
cp -a cpuid-20230505 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1685492862
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export FCFLAGS="$FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export FFLAGS="$FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export CXXFLAGS="$CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
make  %{?_smp_mflags}

pushd ../buildavx2
export CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3"
export CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3"
export FFLAGS="$FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3"
export FCFLAGS="$FCFLAGS -m64 -march=x86-64-v3"
export LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3"
make  %{?_smp_mflags}
popd

%install
export SOURCE_DATE_EPOCH=1685492862
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/cpuid
cp %{_builddir}/cpuid-%{version}/LICENSE %{buildroot}/usr/share/package-licenses/cpuid/4cc77b90af91e615a64ae04893fdffa7939db84c || :
pushd ../buildavx2/
%make_install_v3
popd
%make_install
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/V3/usr/bin/cpuid
/usr/bin/cpuid
/usr/bin/cpuinfo2cpuid

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/cpuid/4cc77b90af91e615a64ae04893fdffa7939db84c

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/cpuid.1.gz
/usr/share/man/man1/cpuinfo2cpuid.1.gz
